[services]
    [services.Instruments.rpc.triggerSendData]
    [services.Instruments.rpc.createKitInstrument]
        parameter = { name = 'Text' }
    [services.Instruments.rpc.removeKitInstrument]
        parameter = { instrumentUUID = 'Data' }
    [services.Instruments.signal.dataChanged]
        parameter = { jsonStrData = 'Text' }
    [services.MusicDevices.rpc.triggerSendMusicDeviceList]
    [services.MusicDevices.rpc.registerForParameterChange]
        parameter = { deviceIdStr = 'Text', voiceIdx = 'Int16' }
    [services.MusicDevices.rpc.unregisterForParameterChange]
        parameter = { deviceIdStr = 'Text', voiceIdx = 'Int16' }
        returns = { instrumentUUID = 'Data', deviceIdStr = 'Text', aNumber = 'Int32' }
    [services.MusicDevices.signal.musicDeviceListChanged]
        parameter = { deviceNameList = 'Text' }
    [services.MusicDevices.signal.parameterChanged]
        parameter =  { deviceId = 'Text', voiceId = 'Int16', paramIdx = 'Int16', commanded = 'Float32', actual = 'Float32'}
